export const wishes = [
  "Today is your day to shine and make a positive impact on the world!",
  "Believe in yourself - you have the strength to overcome any challenge.",
  "May your day be filled with joy, laughter, and wonderful surprises.",
  "You are capable of amazing things. Trust the journey ahead.",
  "Embrace today with an open heart and watch the magic unfold.",
  "Your kindness and compassion make the world a better place.",
  "Every step you take today brings you closer to your dreams.",
  "You are loved, valued, and appreciated more than you know.",
  "May today bring you peace, clarity, and beautiful moments.",
  "Your positive energy is contagious - share it freely today!",
  "You have the power to create the life you've always imagined.",
  "Today is a fresh start, full of endless possibilities for you.",
  "Your smile has the power to brighten someone's entire day.",
  "Trust in your abilities - you are stronger than you think.",
  "May happiness and success follow you wherever you go today.",
  "You are exactly where you need to be on your unique journey.",
  "Your creativity and talents are gifts to be shared with the world.",
  "Today is the perfect day to be grateful for all you have.",
  "You deserve all the wonderful things coming your way.",
  "Your determination and resilience will lead you to great things.",
  "May today be filled with love, laughter, and unforgettable memories.",
  "You have the courage to face anything that comes your way.",
  "Your presence makes a difference - never forget your worth.",
  "Today brings new opportunities to grow, learn, and thrive.",
  "You are a beacon of light in this world - let it shine bright!",
];
